// <auto-generated />
namespace Finance.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class updateEvent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateEvent));
        
        string IMigrationMetadata.Id
        {
            get { return "202004241436574_updateEvent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
